import './globals.css'
import { Inter } from 'next/font/google'
import Menu from '../../components/Menu/Menu'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <head>
        <title>Modal</title>
      </head>
      <body>
        <div className="flex min-h-screen flex-col items-center justify-between p-4">
          <h1>Modal</h1>
          <div className="absolute top-0 left-0 m-4 p-10">
            <Menu />
          </div>
          <main>{children}</main>
        </div>
      </body>
    </html>
  )
}
